name: Build and run

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron: '*/15 * * * *'

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      cache-key: runelite-versions

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'

      # get cache from previous run ID
      - uses: actions/cache/restore@v4
        id: cache-restore
        with:
          path: ${{ env.cache-key }}.json
          key: ${{ env.cache-key }}

      - name: Run application
        run: mvn compile exec:java -Dexec.mainClass=dev.burak.rlversionchecker.Main
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
          AZURE_URL: ${{ secrets.AZURE_URL }}
          AZURE_PIPELINE_ID: ${{ secrets.AZURE_PIPELINE_ID }}

      - name: Delete Previous Cache
        if: ${{ steps.cache-restore.outputs.cache-hit }}
        continue-on-error: true
        run: |
          gh extension install actions/gh-actions-cache
          gh actions-cache delete "${{ env.cache-key }}" --confirm
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRIGGER_REPO_URI: ${{ secrets.TRIGGER_REPO_URI }}
          TRIGGER_WORKFLOW_ID: ${{ secrets.REPO_URI }}
          REPO_REF: master

      - uses: actions/cache/save@v4
        with:
          path: ${{ env.cache-key }}.json
          key: ${{ env.cache-key }}
