name: Build and run

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/15 * * * *'

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CACHE_FILE: cache-file.json

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'

      - name: Download JSON from Azure Blob Storage
        run: |
          az storage blob download \
            --name ${{ env.CACHE_FILE }} \
            --file ${{ env.CACHE_FILE }} \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --container-name ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }} \
            --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} || echo "No cache found"

      - name: Run application
        run: mvn compile exec:java -Dexec.mainClass=dev.burak.rlversionchecker.Main
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_DISPATCH_PAT }}
          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
          AZURE_URL: ${{ secrets.AZURE_URL }}
          AZURE_PIPELINE_ID: ${{ secrets.AZURE_PIPELINE_ID }}
          TRIGGER_WORKFLOW_ID: ${{ secrets.TRIGGER_WORKFLOW_ID }}
          REPO_URI: ${{ secrets.TRIGGER_REPO_URI }}
          REPO_REF: main

      - name: Upload JSON to Azure Blob Storage
        run: |
          az storage blob upload \
            --name ${{ env.CACHE_FILE }} \
            --file ${{ env.CACHE_FILE }} \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --container-name ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }} \
            --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} \
            --overwrite true