name: Build and run

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CACHE_FILE: cache-file.json

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build . -t ghcr.io/${{ github.repository }}/runelite-version-checker:latest

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/runelite-version-checker:latest